// Generated by gencpp from file ros_face_recognition/Detect.msg
// DO NOT EDIT!


#ifndef ROS_FACE_RECOGNITION_MESSAGE_DETECT_H
#define ROS_FACE_RECOGNITION_MESSAGE_DETECT_H

#include <ros/service_traits.h>


#include <ros_face_recognition/DetectRequest.h>
#include <ros_face_recognition/DetectResponse.h>


namespace ros_face_recognition
{

struct Detect
{

typedef DetectRequest Request;
typedef DetectResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Detect
} // namespace ros_face_recognition


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_face_recognition::Detect > {
  static const char* value()
  {
    return "f143431592089c2f0b0ac5b4a093e5e0";
  }

  static const char* value(const ::ros_face_recognition::Detect&) { return value(); }
};

template<>
struct DataType< ::ros_face_recognition::Detect > {
  static const char* value()
  {
    return "ros_face_recognition/Detect";
  }

  static const char* value(const ::ros_face_recognition::Detect&) { return value(); }
};


// service_traits::MD5Sum< ::ros_face_recognition::DetectRequest> should match 
// service_traits::MD5Sum< ::ros_face_recognition::Detect > 
template<>
struct MD5Sum< ::ros_face_recognition::DetectRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_face_recognition::Detect >::value();
  }
  static const char* value(const ::ros_face_recognition::DetectRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_face_recognition::DetectRequest> should match 
// service_traits::DataType< ::ros_face_recognition::Detect > 
template<>
struct DataType< ::ros_face_recognition::DetectRequest>
{
  static const char* value()
  {
    return DataType< ::ros_face_recognition::Detect >::value();
  }
  static const char* value(const ::ros_face_recognition::DetectRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_face_recognition::DetectResponse> should match 
// service_traits::MD5Sum< ::ros_face_recognition::Detect > 
template<>
struct MD5Sum< ::ros_face_recognition::DetectResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_face_recognition::Detect >::value();
  }
  static const char* value(const ::ros_face_recognition::DetectResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_face_recognition::DetectResponse> should match 
// service_traits::DataType< ::ros_face_recognition::Detect > 
template<>
struct DataType< ::ros_face_recognition::DetectResponse>
{
  static const char* value()
  {
    return DataType< ::ros_face_recognition::Detect >::value();
  }
  static const char* value(const ::ros_face_recognition::DetectResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_FACE_RECOGNITION_MESSAGE_DETECT_H
