// Generated by gencpp from file ros_face_recognition/FaceRequest.msg
// DO NOT EDIT!


#ifndef ROS_FACE_RECOGNITION_MESSAGE_FACEREQUEST_H
#define ROS_FACE_RECOGNITION_MESSAGE_FACEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_face_recognition
{
template <class ContainerAllocator>
struct FaceRequest_
{
  typedef FaceRequest_<ContainerAllocator> Type;

  FaceRequest_()
    {
    }
  FaceRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::ros_face_recognition::FaceRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_face_recognition::FaceRequest_<ContainerAllocator> const> ConstPtr;

}; // struct FaceRequest_

typedef ::ros_face_recognition::FaceRequest_<std::allocator<void> > FaceRequest;

typedef boost::shared_ptr< ::ros_face_recognition::FaceRequest > FaceRequestPtr;
typedef boost::shared_ptr< ::ros_face_recognition::FaceRequest const> FaceRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_face_recognition::FaceRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_face_recognition::FaceRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ros_face_recognition

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'ros_face_recognition': ['/home/sz/omniWheelCareRobot/rosCode/src/ros-face-recognition/msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ros_face_recognition::FaceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_face_recognition::FaceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_face_recognition::FaceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_face_recognition::FaceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_face_recognition::FaceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_face_recognition::FaceRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_face_recognition::FaceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::ros_face_recognition::FaceRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_face_recognition::FaceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_face_recognition/FaceRequest";
  }

  static const char* value(const ::ros_face_recognition::FaceRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_face_recognition::FaceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
";
  }

  static const char* value(const ::ros_face_recognition::FaceRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_face_recognition::FaceRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FaceRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_face_recognition::FaceRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::ros_face_recognition::FaceRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // ROS_FACE_RECOGNITION_MESSAGE_FACEREQUEST_H
