// Generated by gencpp from file ros_face_recognition/Face.msg
// DO NOT EDIT!


#ifndef ROS_FACE_RECOGNITION_MESSAGE_FACE_H
#define ROS_FACE_RECOGNITION_MESSAGE_FACE_H

#include <ros/service_traits.h>


#include <ros_face_recognition/FaceRequest.h>
#include <ros_face_recognition/FaceResponse.h>


namespace ros_face_recognition
{

struct Face
{

typedef FaceRequest Request;
typedef FaceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Face
} // namespace ros_face_recognition


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_face_recognition::Face > {
  static const char* value()
  {
    return "256cd47e72fed629e24eadd8e05da58a";
  }

  static const char* value(const ::ros_face_recognition::Face&) { return value(); }
};

template<>
struct DataType< ::ros_face_recognition::Face > {
  static const char* value()
  {
    return "ros_face_recognition/Face";
  }

  static const char* value(const ::ros_face_recognition::Face&) { return value(); }
};


// service_traits::MD5Sum< ::ros_face_recognition::FaceRequest> should match 
// service_traits::MD5Sum< ::ros_face_recognition::Face > 
template<>
struct MD5Sum< ::ros_face_recognition::FaceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_face_recognition::Face >::value();
  }
  static const char* value(const ::ros_face_recognition::FaceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_face_recognition::FaceRequest> should match 
// service_traits::DataType< ::ros_face_recognition::Face > 
template<>
struct DataType< ::ros_face_recognition::FaceRequest>
{
  static const char* value()
  {
    return DataType< ::ros_face_recognition::Face >::value();
  }
  static const char* value(const ::ros_face_recognition::FaceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_face_recognition::FaceResponse> should match 
// service_traits::MD5Sum< ::ros_face_recognition::Face > 
template<>
struct MD5Sum< ::ros_face_recognition::FaceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_face_recognition::Face >::value();
  }
  static const char* value(const ::ros_face_recognition::FaceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_face_recognition::FaceResponse> should match 
// service_traits::DataType< ::ros_face_recognition::Face > 
template<>
struct DataType< ::ros_face_recognition::FaceResponse>
{
  static const char* value()
  {
    return DataType< ::ros_face_recognition::Face >::value();
  }
  static const char* value(const ::ros_face_recognition::FaceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_FACE_RECOGNITION_MESSAGE_FACE_H
