// Generated by gencpp from file ros_face_recognition/NameRequest.msg
// DO NOT EDIT!


#ifndef ROS_FACE_RECOGNITION_MESSAGE_NAMEREQUEST_H
#define ROS_FACE_RECOGNITION_MESSAGE_NAMEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_face_recognition
{
template <class ContainerAllocator>
struct NameRequest_
{
  typedef NameRequest_<ContainerAllocator> Type;

  NameRequest_()
    : label()
    , name()  {
    }
  NameRequest_(const ContainerAllocator& _alloc)
    : label(_alloc)
    , name(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _label_type;
  _label_type label;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _name_type;
  _name_type name;





  typedef boost::shared_ptr< ::ros_face_recognition::NameRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_face_recognition::NameRequest_<ContainerAllocator> const> ConstPtr;

}; // struct NameRequest_

typedef ::ros_face_recognition::NameRequest_<std::allocator<void> > NameRequest;

typedef boost::shared_ptr< ::ros_face_recognition::NameRequest > NameRequestPtr;
typedef boost::shared_ptr< ::ros_face_recognition::NameRequest const> NameRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_face_recognition::NameRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_face_recognition::NameRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ros_face_recognition

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'ros_face_recognition': ['/home/sz/omniWheelCareRobot/rosCode/src/ros-face-recognition/msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ros_face_recognition::NameRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_face_recognition::NameRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_face_recognition::NameRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_face_recognition::NameRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_face_recognition::NameRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_face_recognition::NameRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_face_recognition::NameRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4db9547d930bab2e833d783a4473ab99";
  }

  static const char* value(const ::ros_face_recognition::NameRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4db9547d930bab2eULL;
  static const uint64_t static_value2 = 0x833d783a4473ab99ULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_face_recognition::NameRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_face_recognition/NameRequest";
  }

  static const char* value(const ::ros_face_recognition::NameRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_face_recognition::NameRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string label\n\
string name\n\
";
  }

  static const char* value(const ::ros_face_recognition::NameRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_face_recognition::NameRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.label);
      stream.next(m.name);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct NameRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_face_recognition::NameRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_face_recognition::NameRequest_<ContainerAllocator>& v)
  {
    s << indent << "label: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.label);
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_FACE_RECOGNITION_MESSAGE_NAMEREQUEST_H
