// Generated by gencpp from file ros_face_recognition/Name.msg
// DO NOT EDIT!


#ifndef ROS_FACE_RECOGNITION_MESSAGE_NAME_H
#define ROS_FACE_RECOGNITION_MESSAGE_NAME_H

#include <ros/service_traits.h>


#include <ros_face_recognition/NameRequest.h>
#include <ros_face_recognition/NameResponse.h>


namespace ros_face_recognition
{

struct Name
{

typedef NameRequest Request;
typedef NameResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Name
} // namespace ros_face_recognition


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_face_recognition::Name > {
  static const char* value()
  {
    return "e8ebf5b25d29d1f53b4d613db1c66b5f";
  }

  static const char* value(const ::ros_face_recognition::Name&) { return value(); }
};

template<>
struct DataType< ::ros_face_recognition::Name > {
  static const char* value()
  {
    return "ros_face_recognition/Name";
  }

  static const char* value(const ::ros_face_recognition::Name&) { return value(); }
};


// service_traits::MD5Sum< ::ros_face_recognition::NameRequest> should match 
// service_traits::MD5Sum< ::ros_face_recognition::Name > 
template<>
struct MD5Sum< ::ros_face_recognition::NameRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_face_recognition::Name >::value();
  }
  static const char* value(const ::ros_face_recognition::NameRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_face_recognition::NameRequest> should match 
// service_traits::DataType< ::ros_face_recognition::Name > 
template<>
struct DataType< ::ros_face_recognition::NameRequest>
{
  static const char* value()
  {
    return DataType< ::ros_face_recognition::Name >::value();
  }
  static const char* value(const ::ros_face_recognition::NameRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_face_recognition::NameResponse> should match 
// service_traits::MD5Sum< ::ros_face_recognition::Name > 
template<>
struct MD5Sum< ::ros_face_recognition::NameResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_face_recognition::Name >::value();
  }
  static const char* value(const ::ros_face_recognition::NameResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_face_recognition::NameResponse> should match 
// service_traits::DataType< ::ros_face_recognition::Name > 
template<>
struct DataType< ::ros_face_recognition::NameResponse>
{
  static const char* value()
  {
    return DataType< ::ros_face_recognition::Name >::value();
  }
  static const char* value(const ::ros_face_recognition::NameResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_FACE_RECOGNITION_MESSAGE_NAME_H
