// Generated by gencpp from file face_recognition_msgs/DetectedFaces.msg
// DO NOT EDIT!


#ifndef FACE_RECOGNITION_MSGS_MESSAGE_DETECTEDFACES_H
#define FACE_RECOGNITION_MSGS_MESSAGE_DETECTEDFACES_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace face_recognition_msgs
{
template <class ContainerAllocator>
struct DetectedFaces_
{
  typedef DetectedFaces_<ContainerAllocator> Type;

  DetectedFaces_()
    : header()
    , names()
    , probability()
    , distances()  {
    }
  DetectedFaces_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , names(_alloc)
    , probability(_alloc)
    , distances(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > , typename ContainerAllocator::template rebind<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::other >  _names_type;
  _names_type names;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _probability_type;
  _probability_type probability;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _distances_type;
  _distances_type distances;





  typedef boost::shared_ptr< ::face_recognition_msgs::DetectedFaces_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::face_recognition_msgs::DetectedFaces_<ContainerAllocator> const> ConstPtr;

}; // struct DetectedFaces_

typedef ::face_recognition_msgs::DetectedFaces_<std::allocator<void> > DetectedFaces;

typedef boost::shared_ptr< ::face_recognition_msgs::DetectedFaces > DetectedFacesPtr;
typedef boost::shared_ptr< ::face_recognition_msgs::DetectedFaces const> DetectedFacesConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::face_recognition_msgs::DetectedFaces_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::face_recognition_msgs::DetectedFaces_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace face_recognition_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'face_recognition_msgs': ['/home/sz/omniWheelCareRobot/rosCode/src/face_recognition/face_recognition_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::face_recognition_msgs::DetectedFaces_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::face_recognition_msgs::DetectedFaces_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::face_recognition_msgs::DetectedFaces_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::face_recognition_msgs::DetectedFaces_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::face_recognition_msgs::DetectedFaces_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::face_recognition_msgs::DetectedFaces_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::face_recognition_msgs::DetectedFaces_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1bb6fcd7b70b16de4f4ea15de19e52e9";
  }

  static const char* value(const ::face_recognition_msgs::DetectedFaces_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1bb6fcd7b70b16deULL;
  static const uint64_t static_value2 = 0x4f4ea15de19e52e9ULL;
};

template<class ContainerAllocator>
struct DataType< ::face_recognition_msgs::DetectedFaces_<ContainerAllocator> >
{
  static const char* value()
  {
    return "face_recognition_msgs/DetectedFaces";
  }

  static const char* value(const ::face_recognition_msgs::DetectedFaces_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::face_recognition_msgs::DetectedFaces_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
string[] names\n\
float64[] probability\n\
float64[] distances\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::face_recognition_msgs::DetectedFaces_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::face_recognition_msgs::DetectedFaces_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.names);
      stream.next(m.probability);
      stream.next(m.distances);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DetectedFaces_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::face_recognition_msgs::DetectedFaces_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::face_recognition_msgs::DetectedFaces_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "names[]" << std::endl;
    for (size_t i = 0; i < v.names.size(); ++i)
    {
      s << indent << "  names[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.names[i]);
    }
    s << indent << "probability[]" << std::endl;
    for (size_t i = 0; i < v.probability.size(); ++i)
    {
      s << indent << "  probability[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.probability[i]);
    }
    s << indent << "distances[]" << std::endl;
    for (size_t i = 0; i < v.distances.size(); ++i)
    {
      s << indent << "  distances[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.distances[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // FACE_RECOGNITION_MSGS_MESSAGE_DETECTEDFACES_H
